# File: examples/train_qlora/internvl_lora_sft_bnb.yaml

model_name_or_path: OpenGVLab/InternVL3-8B
quantization_bit: 4
quantization_method: bnb
double_quantization: false
trust_remote_code: true


### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: flare_dataset
template: intern_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4


### output
output_dir: saves/internvl/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: linear
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
